version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      networks:
        - cbase

    cbase:
      build: .
      environment:
        - DB_HOST=mariadb
        - DB_NAME=test
        - DB_USER=user
        - DB_PASS=password
        - BASE_URI http://localhost:8080
      ports:
        - "8080:80"
      networks:
        - cbase
      volumes:
        - ./public:/var/www/html/public
        - ./private:/var/www/html/private

networks:
  cbase:
    driver: bridge
